name: 'todo-backlinks'
description: 'Link from issue 123 to source lines containing `TODO(#123)` and similar'
author: Jeremy Kun
branding:
  icon: 'link'
  color: 'orange'
outputs:
  affected-issues:
    description: 'comma-separated list of affected issues'
runs:
  using: 'docker'
  image: 'Dockerfile'
