name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install pip dependencies
      run: pip install -r requirements.txt

    - name: Run Python unit tests
      run: python3 -m pytest

    - name: Verify that the Docker image for the action builds
      run: docker build . --file Dockerfile

    - name: Integration test
      id: integration
      uses: ./
      with:
        # only check for TODOs in this file, to avoid conflicts
        # with readmes, unit tests, etc.
        git_grep_pathspecs: ":/tests/integration.py"
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
        DRY_RUN: true

    - name: Output the outputs of the integration test of the action
      run: |
        echo "affected-issues = ${{ steps.integration.outputs.affected-issues }}"

    - name: Verify integration test results
      run: python3 -m pytest tests/integration.py
      env:
        AFFECTED_ISSUES: ${{ steps.integration.outputs.affected-issues }}
